version: 2

jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: docker-compose build

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
