version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - run: docker-compose build

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
