version: 2

jobs:
  build-and-publish:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker-compose build
      - run:
          name: Login to Docker Hub
          command: |
            USERNAME=$(echo $DOCKER_HUB_USERNAME | base64 -d)
            PASSWORD=$(echo $DOCKER_HUB_PASSWORD | base64 -d)
            docker login --username $USERNAME --password $PASSWORD
      - run:
          name: Publish the image to Docker Hub
          command: docker push rlewan/nginx-static:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: master
