version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker-compose

  publish:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - run: echo "Hello, World!"


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
