version: 2

jobs:
  build-and-publish:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker-compose build
      - run:
          name: Publish the image to Docker Hub
          command: docker push rlewan/nginx-static:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-publish
