version: 2

jobs:
  build:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker-compose build
  publish:
    docker:
      - image: docker/compose:1.23.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish image to Docker Hub
          command: docker-compose push


workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
